Envoi BDD projet
WildCodeSchool-2023-09/php-p2-strashelp pull request #1
Opened 2023-11-06 15:45 UTC by elisechldn

2023-11-06 15:46 UTC, Williamlh33 approved these changes

2023-11-06 20:27 UTC, Carcali approved these changes

2023-11-07 06:46 UTC, vincentr-wcs requested changes
Nom des tables et des colonnes en minuscule et au singulier c'est une bonne pratique notamment pour symfony. Doc : https://sql.sh/1396-nom-table-colonne

2023-11-07 11:25 UTC, Carcali approved these changes
Bons changements !

2023-11-07 12:51 UTC, vincentr-wcs approved these changes
Bon travail !

2023-11-07 12:52 UTC, merged