ok
WildCodeSchool-2023-09/php-p2-strashelp pull request #2
Opened 2023-11-06 16:06 UTC by Mrsalhi

2023-11-06 20:28 UTC, Williamlh33 approved these changes

2023-11-06 20:41 UTC, Carcali approved these changes

2023-11-07 07:08 UTC, vincentr-wcs reviewed
Je t'ai fait quelques recommandations de bonnes pratiques. Fait aussi attention à l'indentation de tes fichiers car tes fichiers deviennent vite difficilement lisibles. N'hésite pas à installer une extension si ce n'est pas fait pour que ça se fasse automatiquement ;) 
Sinon très bon travail ! 👍

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/Components/_navbar.html.twig
> +	 <div class="inscrip">
Il faudrait mieux mettre un nom de class plus explicite et éviter les abréviations comme par exemple authentification-button

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/annonces/_annonces.html.twig
> +{% block content %} 2eme essai {% endblock %}
Je comprends que tu voulais tester que ça fonctionne mais du coup c'est du test donc faut éviter de le push et l'enlever au moment du commit

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/connexion/connexion.html.twig
> +{% block content %}3eme essai{% endblock %}
idem ici

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/contact/contact.html.twig
> +{% block content %}sajid1{% endblock %}
idem ici

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/deposeruneannonce/deposeruneannonce.html.twig
> +{% block content %} 2eme essai {% endblock %}
idem ici

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/inscription/inscription.html.twig
> +{% block content %} sajid3 {% endblock %}
idem ici

2023-11-07 07:08 UTC, vincentr-wcs commented on src/View/layout.html.twig
> +		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.17.6/dist/css/uikit.min.css"/>
Pour alléger le head ici tu aurais pu mettre en import dans ta feuille de style "style.css" en premier

2023-11-08 20:26 UTC, vincentr-wcs requested changes
Une dernière petite modif et ça sera bon :)

2023-11-08 20:26 UTC, vincentr-wcs commented on src/View/Components/_navbar.html.twig
> +</ul></div></nav>
Attention ici tu dois fermé ta div avant la balise ul

2023-11-09 09:30 UTC, vincentr-wcs approved these changes

2023-11-09 09:30 UTC, merged