Réalisation login
WildCodeSchool-2023-09/php-p2-strashelp pull request #3
Opened 2023-11-06 19:31 UTC by elisechldn

2023-11-06 20:15 UTC, Williamlh33 approved these changes
nickel

2023-11-06 20:23 UTC, Williamlh33 requested changes
on va devoir push à nouveau ! il n'y a pas eu sauvegarde des changements apres grump ....

2023-11-08 09:39 UTC, yavuzkutuk commented
@elisechldn il y a comme un problème

2023-11-08 10:11 UTC, elisechldn commented
J'arrive pas à push la version correcte, aled.

2023-11-08 15:28 UTC, Williamlh33 approved these changes

2023-11-08 20:49 UTC, vincentr-wcs requested changes
Petits détails à modifier sinon c'est très bien !

2023-11-08 20:49 UTC, vincentr-wcs commented on public/assets/css/_login.css
> +@import url('https://fonts.cdnfonts.com/css/poppins');
Pour éviter de faire un import dans tous les fichiers css, faudrait le mettre dans un fichier global en css. J'ai vu sur d'autres PR des variables.css. Il faudra donc le déplacer à ce moment là

2023-11-08 20:49 UTC, vincentr-wcs commented on src/Controller/UserController.php
> +            $credentials = array_map('htmlentities', $credentials);
Pas de htmlentities avec twig. Il est géré par défaut

2023-11-08 20:49 UTC, vincentr-wcs commented on src/Controller/UserController.php
> +                    header('Location: /login');
Il vaut mieux renvoyer l'utilisateur vers une autre page pour lui indiquer que tout a fonctionné. 
Si tu le renvoies sur la même page il peut avoir un doute sur le fait que ça ait marché ou non.

2023-11-10 10:49 UTC, vincentr-wcs approved these changes

2023-11-10 10:49 UTC, merged