Register form
WildCodeSchool-2023-09/php-p2-strashelp pull request #6
Opened 2023-11-10 22:13 UTC by Williamlh33

2023-11-11 18:49 UTC, elisechldn requested changes
La table "Users" n'existe plus et s'appelle "User", il faudra changer cela.

2023-11-13 13:27 UTC, vincentr-wcs commented
Conflit à régler @Williamlh33

2023-11-14 10:11 UTC, Carcali approved these changes

2023-11-14 13:32 UTC, elisechldn approved these changes

2023-11-14 20:40 UTC, vincentr-wcs requested changes
Super travail encore une fois juste un petit changement et on est good :)

2023-11-14 20:40 UTC, vincentr-wcs commented on src/View/layout.html.twig
> +		<link rel="stylesheet" href="/assets/css/variables.css">
Il faut que tu déplaces ces fichiers css dans style.css qui est votre point d'entrée de vos fichiers css. En plus variables.css est déjà importé dans ce fichier

2023-11-15 20:16 UTC, Williamlh33 commented on src/View/layout.html.twig
> +		<link rel="stylesheet" href="/assets/css/variables.css">
c'est fait

2023-11-16 10:09 UTC, vincentr-wcs approved these changes

2023-11-16 10:09 UTC, merged