annonce back et intégrétation twig grump1
WildCodeSchool-2023-09/php-p2-strashelp pull request #7
Opened 2023-11-10 22:51 UTC by Williamlh33

2023-11-11 18:38 UTC, elisechldn approved these changes
Top, bien joué !

2023-11-13 13:07 UTC, vincentr-wcs requested changes

2023-11-13 13:07 UTC, vincentr-wcs commented on src/View/annonces/_annonces.html.twig
> +			{% endfor %}
Il manque pas une div fermante avec la class container et la section ?

2023-11-14 10:10 UTC, Carcali approved these changes

2023-11-14 20:22 UTC, vincentr-wcs requested changes

2023-11-14 20:22 UTC, vincentr-wcs commented on src/Model/AnnoncesManager.php
> +    public const TABLE = 'ads';
Attention la database a été changé hier par Elise elle s'appelle maintenant ad

2023-11-14 20:22 UTC, vincentr-wcs commented on src/View/annonces/_annonces.html.twig
> +		{% endfor %}
le endfor me paraît mal placer est ce qui devrait pas être un cran dessus ?

2023-11-14 20:30 UTC, Williamlh33 commented on src/Model/AnnoncesManager.php
> +    public const TABLE = 'ads';
ok je fais ca de suite

2023-11-14 20:30 UTC, Williamlh33 commented on src/View/annonces/_annonces.html.twig
> +		{% endfor %}
ok je fais ca de suite

2023-11-14 20:30 UTC, Williamlh33 commented on src/View/annonces/_annonces.html.twig
> +		{% endfor %}
mais ca fonctionne oui

2023-11-16 07:37 UTC, vincentr-wcs approved these changes
Super travail

2023-11-16 07:37 UTC, merged